config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "tasks#index"
  resources :tasks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3, maximum: 20 }
  validates :description, allow_blank: true, length: { minimum: 3, maximum: 500 }
  validates :start_time, presence: true
  validate :start_time_is_now_or_later
  validate :end_time_is_one_day_after_the_start_time

  enum status: { not_started: 0, in_progress: 1, closed: 2 }

  belongs_to :user

  private

  def start_time_is_now_or_later
    if start_time.beginning_of_day < Time.current.beginning_of_day
      errors.add(:start_time, "は本日以降にしか設定できません")
    end
  end

  def end_time_is_one_day_after_the_start_time
    if end_time.present? && end_time < start_time.tomorrow.beginning_of_day
      errors.add(:end_time, "は#{I18n.t 'activerecord.attributes.task.start_time'}の翌日以降からしか設定できません")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = current_user.tasks
    @tasks = @tasks.where(status: params[:status]) if params[:status].present?
    @paginate_tasks = @tasks.page(params[:page]).per(15)
  end

  # GET /tasks/1 or /tasks/1.json
  def show
    @tasks = current_user.tasks
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = current_user.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy!

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :description, :start_time, :end_time, :status)
    end

    def correct_user
      @task = current_user.tasks.find_by(id: params[:id])
      redirect_to root_url unless @task
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def colord_button(task)
    case task.status.to_sym
    when :not_started
      "btn-danger"
    when :in_progress
      "btn-warning"
    when :closed
      "btn-primary"
    end
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <ul class="alert alert-warning" style="list-style:none;">
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% if notice %>
  <div class="alert alert-success">
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger">
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_global_navigation.html.erb
<nav class="navbar bg-body-tertiary">
  <div class="container">
    <a class="navbar-brand" href="/"><%= t "activerecord.models.task" %>リスト</a>
    <div>
      <% if current_user %>
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <%= button_to "ログアウト", destroy_user_session_path, class: "nav-link", method: :delete %>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
          </li>
        </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/global_navigation" %>
    <div class="container my-4">
      <%= render "layouts/flash_messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_callender.html.erb
<%= month_calendar events: tasks do |date, tasks| %>
  <%= date.day %><br>
  <% tasks.each.with_index(1) do |task, i| %>
    <%= link_to i, task, style: "text-decoration:none;" %><br>
  <% end %>
<% end %>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_with(model: task) do |form| %>
      <%= render "layouts/error_messages", model: form.object %>

      <% if params[:action] == "new" || params[:action] == "create" %>
        <div class="mb-3">
          <%= form.label :title, style: "display: block" %>
          <%= form.text_field :title, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :description, style: "display: block" %>
          <%= form.text_area :description, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :start_time, style: "display: block" %>
          <%= form.datetime_field :start_time, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :end_time, style: "display: block" %>
          <%= form.datetime_field :end_time, class: "form-control" %>
        </div>
      <% end %>

      <% if params[:action] == "edit" || params[:action] == "update" %>
        <div class="mb-3">
          <%= form.label :status, style: "display: block" %>
          <%= form.select :status, Task.statuses.keys.map {|k| [I18n.t("enums.task.status.#{k}"), k]}, {}, { class: "form-control" } %>
        </div>
      <% end %>

      <div class="mb-3">
        <%= form.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/_task.html.erb
<tr>
  <td><%= task.title %></td>
  <td><%= l task.start_time, format: :long %></td>
  <td><%= l task.end_time, format: :long if task.end_time.present? %></td>
  <td><%= link_to task.status_i18n, task_path(task), class: "btn #{colord_button(task)}" %></td>
</tr>

app/views/tasks/edit.html.erb
<h1><%= t "activerecord.models.task" %>編集</h1>

<div class="row">
  <div class="col-md-8">
    <table class="table table-bordered">
      <tr>
        <th><%= t "activerecord.attributes.task.title" %></th>
        <td><%= link_to_if params[:action] == "index", @task.title, @task %></td>
      </tr>
      <tr>
        <th><%= t "activerecord.attributes.task.description" %></th>
        <td><%= @task.description %></td>
      </tr>
      <tr>
        <th><%= t "activerecord.attributes.task.start_time" %></th>
        <td><%= l @task.start_time, format: :long %></td>
      </tr>
      <tr>
        <th><%= t "activerecord.attributes.task.end_time" %></th>
        <td><%= l @task.end_time, format: :long if @task.end_time.present? %></td>
      </tr>
    </table>

  </div>
</div>
<%= render "form", task: @task %>

<div class="d-flex">
  <%= link_to "#{ t "activerecord.models.task"}詳細", @task, class: "btn btn-primary me-2" %>
  <%= link_to "リストへ戻る", tasks_path, class: "btn btn-secondary me-2" %>
</div>

app/views/tasks/index.html.erb
<h1><%= t "activerecord.models.task" %>リスト</h1>

<div class="row">
  <div class="col-md-8">
    <%= form_with(url: tasks_path, method: :get) do |f| %>
      <div class="mb-3 d-flex">
        <%= f.select :status, Task.statuses.keys.map {|k| [I18n.t("enums.task.status.#{k}"), k]},
                     { include_blank: "すべて見る", selected: params[:status] },
                     { class: "form-control w-25 me-3" } %>
        <%= f.submit "検索する", class: "btn btn-primary" %>
      </div>
    <% end %>
    <table class="table table-bordered table-striped">
      <tr>
        <th><%= t "activerecord.attributes.task.title" %></th>
        <th><%= t "activerecord.attributes.task.start_time" %></th>
        <th><%= t "activerecord.attributes.task.end_time" %></th>
        <th><%= t "activerecord.attributes.task.status" %></th>
      </tr>
      <%= render @paginate_tasks %>
    </table>
    <%= paginate @paginate_tasks, theme: "bootstrap-5" %>
  </div>
  <div class="col-md-4">
    <%= render "callender", tasks: @tasks %>
  </div>
</div>


<%= link_to "新規#{ t "activerecord.models.task"}の作成", new_task_path, class: "btn btn-primary me-2" %>

app/views/tasks/new.html.erb
<h1>新規<%= t "activerecord.models.task" %></h1>

<%= render "form", task: @task %>

<div>
  <%= link_to "リストへ戻る", tasks_path, class: "btn btn-secondary me-2" %>
</div>

app/views/tasks/show.html.erb
<h1><%= t "activerecord.models.task" %>詳細</h1>

<div class="row">
  <div class="col-md-8">
    <table class="table table-bordered">
      <tr>
        <th><%= t "activerecord.attributes.task.title" %></th>
        <td><%= link_to_if params[:action] == "index", @task.title, @task %></td>
      </tr>
      <tr>
        <th><%= t "activerecord.attributes.task.description" %></th>
        <td><%= @task.description %></td>
      </tr>
      <tr>
        <th><%= t "activerecord.attributes.task.start_time" %></th>
        <td><%= l @task.start_time, format: :long %></td>
      </tr>
      <tr>
        <th><%= t "activerecord.attributes.task.end_time" %></th>
        <td><%= l @task.end_time, format: :long if @task.end_time.present? %></td>
      </tr>
      <tr>
        <th><%= t "activerecord.attributes.task.status" %></th>
        <td><span class="btn <%= colord_button(@task) %>"><%= @task.status_i18n %></span></td>
      </tr>
    </table>
  </div>
  <div class="col-md-4">
    <%= render "callender", tasks: @tasks %>
  </div>
</div>

<div class="d-flex">
  <%= link_to "この#{ t "activerecord.models.task" }を編集", edit_task_path(@task), class: "btn btn-warning me-2" %>
  <%= link_to "リストへ戻る", tasks_path, class: "btn btn-secondary me-2" %>
  <%= button_to "この#{ t "activerecord.models.task" }を削除する", @task, method: :delete, class: "btn btn-danger me-2" %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <ul class="alert alert-warning" style="list-style:none;">
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>